version: '3.8'

services:
  tradingbot:
    build: .
    container_name: tradingbot
    environment:
      - ENV=production
    ports:
      - "7860:7860"
    volumes:
      - ./:/app
    working_dir: /app
    command: python scripts/run_dashboard.py 