from typing import Any, Dict, List, Optional, Union
import numpy as np
import pandas as pd

# Основные типы plotly
class Figure: ...
class Layout: ...
class Data: ...

def graph_objects() -> Any: ...
def express() -> Any: ...
def subplots() -> Any: ... 