"""
Модуль технического анализа.

Содержит декомпозированные компоненты для технического анализа:
индикаторы, структура рынка, генерация сигналов.
"""

# Индикаторы
from .indicators import (
    calc_accumulation_distribution,
    calc_adx,
    calc_aroon,
    calc_atr,
    calc_awesome_oscillator,
    calc_bollinger_bands,
    calc_cci,
    calc_cci_oscillator,
    calc_chaikin_money_flow,
    calc_dema,
    calc_donchian_channels,
    calc_ema,
    calc_historical_volatility,
    calc_ichimoku,
    calc_keltner_channels,
    calc_macd,
    calc_mfi,
    calc_momentum,
    calc_natr,
    calc_obv,
    calc_parabolic_sar,
    calc_roc,
    calc_rsi,
    calc_sma,
    calc_standard_deviation,
    calc_stochastic,
    calc_tema,
    calc_ultimate_oscillator,
    calc_volume_ema,
    calc_volume_price_trend,
    calc_volume_profile,
    calc_volume_ratio,
    calc_volume_sma,
    calc_vwap,
    calc_williams_r,
    calc_wma,
    calculate_returns,
    detect_divergence,
    validate_ohlcv_data,
)

# Структура рынка
from .market_structure import (
    analyze_market_structure,
    analyze_volume_profile,
    calculate_fibonacci_levels,
    calculate_pivot_points,
    detect_breakouts,
    detect_divergence_patterns,
    detect_trend_direction,
    find_swing_points,
    identify_chart_patterns,
    identify_consolidation_zones,
    identify_support_resistance_levels,
)

# Генерация сигналов
from .signal_generation import (
    calculate_signal_strength,
    combine_signals,
    generate_breakout_signals,
    generate_composite_signal,
    generate_divergence_signals,
    generate_momentum_signals,
    generate_pattern_signals,
    generate_trend_signals,
    validate_signal,
)

# Утилиты
from .utils import (
    TechnicalAnalysisCache,
    clean_cache,
    convert_to_datetime,
    convert_to_decimal,
    create_empty_indicator_result,
    create_empty_technical_result,
    extract_ohlcv_components,
    normalize_data,
    validate_indicator_data,
    validate_market_data,
)

__all__ = [
    # Indicators
    "calc_sma",
    "calc_ema",
    "calc_wma",
    "calc_dema",
    "calc_tema",
    "calc_bollinger_bands",
    "calc_parabolic_sar",
    "calc_ichimoku",
    "calc_macd",
    "calc_adx",
    "calc_cci",
    "calc_aroon",
    "calc_rsi",
    "calc_stochastic",
    "calc_williams_r",
    "calc_momentum",
    "calc_roc",
    "calc_mfi",
    "calc_obv",
    "calc_cci_oscillator",
    "calc_ultimate_oscillator",
    "calc_awesome_oscillator",
    "calc_volume_sma",
    "calc_volume_ema",
    "calc_volume_ratio",
    "calc_volume_profile",
    "calc_vwap",
    "calc_accumulation_distribution",
    "calc_chaikin_money_flow",
    "calc_volume_price_trend",
    "calc_atr",
    "calc_natr",
    "calc_keltner_channels",
    "calc_donchian_channels",
    "calc_standard_deviation",
    "calc_historical_volatility",
    "validate_ohlcv_data",
    "calculate_returns",
    "detect_divergence",
    # Market structure
    "identify_support_resistance_levels",
    "detect_trend_direction",
    "find_swing_points",
    "calculate_fibonacci_levels",
    "identify_chart_patterns",
    "analyze_market_structure",
    "detect_breakouts",
    "calculate_pivot_points",
    "identify_consolidation_zones",
    "analyze_volume_profile",
    "detect_divergence_patterns",
    # Signal generation
    "generate_trend_signals",
    "generate_momentum_signals",
    "generate_breakout_signals",
    "generate_divergence_signals",
    "generate_pattern_signals",
    "combine_signals",
    "calculate_signal_strength",
    "validate_signal",
    "generate_composite_signal",
    # Utils
    "validate_indicator_data",
    "extract_ohlcv_components",
    "create_empty_technical_result",
    "create_empty_indicator_result",
    "convert_to_decimal",
    "convert_to_datetime",
    "clean_cache",
    "validate_market_data",
    "normalize_data",
    "TechnicalAnalysisCache",
]
