# -*- coding: utf-8 -*-
"""Типы паттернов для анализа рынка."""

from enum import Enum


class PatternType(Enum):
    """Типы паттернов крупного капитала."""

    WHALE_ABSORPTION = "whale_absorption"
    MM_SPOOFING = "mm_spoofing"
    ICEBERG_DETECTION = "iceberg_detection"
    LIQUIDITY_GRAB = "liquidity_grab"
    PUMP_AND_DUMP = "pump_and_dump"
    STOP_HUNTING = "stop_hunting"
    ACCUMULATION = "accumulation"
    DISTRIBUTION = "distribution"

    # Добавленные промышленные типы для паттернов торговли и технического анализа
    VOLATILITY_EXPANSION = "volatility_expansion"
    VOLATILITY_CONTRACTION = "volatility_contraction"
    VOLATILITY_BREAKOUT = "volatility_breakout"
    SQUEEZE = "squeeze"
    EXPANSION_BREAKOUT = "expansion_breakout"
    VOLUME_SPIKE = "volume_spike"
    VOLUME_CLIMAX = "volume_climax"
    VOLUME_DIVERGENCE = "volume_divergence"
    VOLUME_BREAKOUT = "volume_breakout"
    LOW_VOLUME_CONSOLIDATION = "low_volume_consolidation"
    HIGH_VOLUME_TREND = "high_volume_trend"
    LIQUIDITY_SWEEP = "liquidity_sweep"
    ORDER_BLOCK = "order_block"
    FAIR_VALUE_GAP = "fair_value_gap"
    INEFFICIENCY = "inefficiency"
    DOJI = "doji"
    HAMMER = "hammer"
    SHOOTING_STAR = "shooting_star"
    ENGULFING_BULLISH = "engulfing_bullish"
    ENGULFING_BEARISH = "engulfing_bearish"
    MORNING_STAR = "morning_star"
    EVENING_STAR = "evening_star"
    THREE_WHITE_SOLDIERS = "three_white_soldiers"
    THREE_BLACK_CROWS = "three_black_crows"
    HANGING_MAN = "hanging_man"
    INVERTED_HAMMER = "inverted_hammer"
    SPINNING_TOP = "spinning_top"
    MARUBOZU = "marubozu"
    ACCUMULATION_DISTRIBUTION = "accumulation_distribution"
    PUMP_AND_DUMP_REVERSAL = "pump_and_dump_reversal"
    PUMP_AND_DUMP_CONTINUATION = "pump_and_dump_continuation"
    PUMP_AND_DUMP_BREAKOUT = "pump_and_dump_breakout"
    PUMP_AND_DUMP_CONSOLIDATION = "pump_and_dump_consolidation"
    PUMP_AND_DUMP_ACCUMULATION = "pump_and_dump_accumulation"
    PUMP_AND_DUMP_DISTRIBUTION = "pump_and_dump_distribution"
    PUMP_AND_DUMP_STOP_HUNTING = "pump_and_dump_stop_hunting"
    PUMP_AND_DUMP_LIQUIDITY_GRAB = "pump_and_dump_liquidity_grab"
    PUMP_AND_DUMP_MM_SPOOFING = "pump_and_dump_mm_spoofing"
    PUMP_AND_DUMP_WHALE_ABSORPTION = "pump_and_dump_whale_absorption"
    PUMP_AND_DUMP_ICEBERG_DETECTION = "pump_and_dump_iceberg_detection"
    SYNTHETIC_NOISE = "synthetic_noise"
    MIRROR_SIGNAL = "mirror_signal"
    ENTANGLEMENT = "entanglement"
    BREAKOUT = "breakout"
    REVERSAL = "reversal"
    CONTINUATION = "continuation"
    CONSOLIDATION = "consolidation"
    TREND = "trend"
    COUNTER_TREND = "counter_trend"
    SIDEWAYS = "sideways"
    RANGING = "ranging"
    CHOPPY = "choppy"
    CLEAN = "clean"
    MESSY = "messy"
    STRONG = "strong"
    WEAK = "weak"
    NEUTRAL = "neutral"
    BULLISH = "bullish"
    BEARISH = "bearish"
    UNKNOWN = "unknown"
