from typing import Any, Optional, Union
import numpy as np

class DBSCAN:
    def __init__(self, eps: float = 0.5, min_samples: int = 5, **kwargs: Any) -> None: ...
    def fit(self, X: np.ndarray) -> 'DBSCAN': ...
    @property
    def labels_(self) -> np.ndarray: ... 