# Strategy Configuration
strategy:
  default_timeframe: 5m
  max_active_strategies: 3
  slippage_model: realistic
  regime_detection_window: 240

# Trading Parameters
trading:
  max_risk_per_trade: 0.01
  position_sizing: dynamic
  leverage: 3x

# Exchange Settings
exchange:
  use_testnet: true
  reconnect_interval: 5

# Simulation Parameters
simulation:
  latency_model: realistic
  slippage_model: average
  capital: 10000

# Machine Learning Settings
ml:
  model_update_interval: 6h
  validation_window: 30d
  use_transformer: true

# Dashboard Configuration
dashboard:
  refresh_interval: 5s
  theme: dark

# ATB Trading System Configuration
# Конфигурация торговой системы ATB

system:
  name: "ATB Trading System"
  version: "1.0.0"
  environment: "development"  # development, staging, production
  debug: true

# Настройки бирж
exchanges:
  bybit:
    api_key: "${BYBIT_API_KEY}"  # Переменная окружения
    secret: "${BYBIT_SECRET}"    # Переменная окружения
    password: "${BYBIT_PASSWORD}"  # Для некоторых бирж
    sandbox: true  # Использовать тестовую среду
    options:
      defaultType: "spot"  # spot, futures, margin
      adjustForTimeDifference: true
      recvWindow: 60000

  binance:
    api_key: "${BINANCE_API_KEY}"
    secret: "${BINANCE_SECRET}"
    sandbox: true
    options:
      defaultType: "spot"
      recvWindow: 60000

# Настройки риск-менеджмента
risk:
  max_risk_per_trade: 0.02      # 2% риска на сделку
  max_daily_loss: 0.05          # 5% максимальный дневной убыток
  max_weekly_loss: 0.15         # 15% максимальный недельный убыток
  max_portfolio_risk: 0.10      # 10% максимальный риск портфеля
  max_correlation: 0.7          # Максимальная корреляция между позициями
  position_sizing_method: "kelly"  # kelly, fixed, volatility
  stop_loss_method: "atr"       # atr, percentage, fixed

# Настройки портфеля
portfolio:
  max_position_size: 0.2        # 20% максимальный размер позиции
  min_position_size: 0.01       # 1% минимальный размер позиции
  target_correlation: 0.3       # Целевая корреляция
  rebalance_threshold: 0.1      # Порог ребалансировки
  max_assets: 10                # Максимум активов в портфеле
  rebalance_frequency: "daily"  # Частота ребалансировки

# Настройки торговли
trading:
  symbols:
    - "BTC/USDT"
    - "ETH/USDT"
    - "BNB/USDT"
    - "ADA/USDT"
    - "SOL/USDT"
  
  timeframes:
    - "1m"
    - "5m"
    - "15m"
    - "1h"
    - "4h"
    - "1d"
  
  strategies:
    - "mean_reversion"
    - "momentum"
    - "breakout"
    - "grid_trading"
    - "dca"
  
  order_types:
    - "market"
    - "limit"
    - "stop_loss"
    - "take_profit"
  
  execution:
    max_slippage: 0.001         # 0.1% максимальный проскальзывание
    retry_attempts: 3           # Количество попыток выполнения ордера
    retry_delay: 1.0            # Задержка между попытками (секунды)

# Настройки машинного обучения
ml:
  models:
    - "lstm"
    - "transformer"
    - "xgboost"
    - "ensemble"
  
  features:
    - "price"
    - "volume"
    - "technical_indicators"
    - "market_sentiment"
    - "on_chain_data"
  
  training:
    lookback_period: 100        # Период для обучения
    validation_split: 0.2       # Доля данных для валидации
    retrain_frequency: "weekly" # Частота переобучения
    min_samples: 1000           # Минимальное количество сэмплов

# Настройки ИИ
ai:
  decision_threshold: 0.7       # Порог уверенности для принятия решений
  confidence_weight: 0.8        # Вес уверенности в принятии решений
  adaptation_speed: 0.1         # Скорость адаптации
  exploration_rate: 0.1         # Скорость исследования новых стратегий
  
  components:
    regime_discovery: true      # Включить обнаружение режимов
    live_adaptation: true       # Включить живую адаптацию
    meta_learning: true         # Включить мета-обучение

# Настройки мониторинга
monitoring:
  prometheus_port: 8001         # Порт для метрик Prometheus
  health_check_interval: 30     # Интервал проверки здоровья (секунды)
  metrics_update_interval: 60   # Интервал обновления метрик (секунды)
  alert_thresholds:
    memory_usage: 0.9           # 90% использования памяти
    cpu_usage: 0.8              # 80% использования CPU
    disk_usage: 0.95            # 95% использования диска
    error_rate: 0.1             # 10% ошибок

# Настройки логирования
logging:
  level: "INFO"                 # DEBUG, INFO, WARNING, ERROR, CRITICAL
  file_rotation: "1 day"        # Ротация логов
  file_retention: "30 days"     # Хранение логов
  format: "detailed"            # simple, detailed, json

# Настройки уведомлений
notifications:
  enabled: true
  channels:
    - "telegram"
    - "email"
    - "slack"
  
  telegram:
    bot_token: "${TELEGRAM_BOT_TOKEN}"
    chat_id: "${TELEGRAM_CHAT_ID}"
  
  email:
    smtp_server: "smtp.gmail.com"
    smtp_port: 587
    username: "${EMAIL_USERNAME}"
    password: "${EMAIL_PASSWORD}"
    recipients:
      - "admin@example.com"
  
  slack:
    webhook_url: "${SLACK_WEBHOOK_URL}"
    channel: "#trading-alerts"

# Настройки базы данных
database:
  type: "postgresql"            # postgresql, sqlite, mysql
  host: "localhost"
  port: 5432
  name: "atb_trading"
  username: "${DB_USERNAME}"
  password: "${DB_PASSWORD}"
  pool_size: 10
  max_overflow: 20

# Настройки кэширования
cache:
  type: "redis"                 # redis, memory, disk
  host: "localhost"
  port: 6379
  password: "${REDIS_PASSWORD}"
  db: 0
  ttl: 3600                     # Время жизни кэша (секунды)

# Настройки безопасности
security:
  api_key_encryption: true      # Шифрование API ключей
  rate_limiting: true           # Ограничение частоты запросов
  ip_whitelist: []              # Белый список IP адресов
  session_timeout: 3600         # Таймаут сессии (секунды)

# Настройки бэкапов
backup:
  enabled: true
  frequency: "daily"            # Частота бэкапов
  retention: "30 days"          # Хранение бэкапов
  location: "backups/"          # Директория для бэкапов
  compression: true             # Сжатие бэкапов

# Настройки эволюции стратегий
evolution:
  enabled: true                 # Включить модуль эволюции стратегий
  database_path: "evolution_strategies.db"  # Путь к базе данных эволюции
  
  # Параметры эволюции
  population_size: 50           # Размер популяции стратегий
  generations: 100              # Количество поколений
  mutation_rate: 0.1            # Частота мутаций
  crossover_rate: 0.8           # Частота скрещивания
  elite_size: 5                 # Размер элиты (лучших стратегий)
  
  # Критерии отбора
  min_accuracy: 0.82            # Минимальная точность стратегии
  min_profitability: 0.05       # Минимальная прибыльность
  max_drawdown: 0.15            # Максимальная просадка
  min_sharpe: 1.0               # Минимальный коэффициент Шарпа
  
  # Ограничения стратегий
  max_indicators: 10            # Максимум индикаторов в стратегии
  max_filters: 5                # Максимум фильтров
  max_entry_rules: 3            # Максимум правил входа
  max_exit_rules: 3             # Максимум правил выхода
  
  # Параметры оптимизации
  optimization:
    enabled: true               # Включить оптимизацию стратегий
    method: "genetic"           # genetic, bayesian, gradient
    max_iterations: 100         # Максимум итераций оптимизации
    parallel_workers: 4         # Количество параллельных процессов
  
  # Параметры тестирования
  testing:
    historical_data_days: 365   # Количество дней исторических данных
    min_trades: 10              # Минимальное количество сделок для оценки
    commission_rate: 0.001      # Комиссия (0.1%)
    slippage_model: "realistic" # realistic, fixed, percentage
  
  # Параметры интеграции
  integration:
    auto_approval: true         # Автоматическое одобрение стратегий
    approval_notifications: true # Уведомления об одобрении
    strategy_weight: 0.1        # Начальный вес одобренных стратегий
    max_approved_strategies: 20 # Максимум одобренных стратегий
  
  # Параметры мониторинга
  monitoring:
    log_evolution_progress: true # Логировать прогресс эволюции
    save_intermediate_results: true # Сохранять промежуточные результаты
    cleanup_old_data: true      # Очищать старые данные
    cleanup_days: 30            # Хранить данные за последние 30 дней

# Социальные сети и новости
social_media:
  enabled: true
  reddit:
    enabled: true
    subreddits:
      - "cryptocurrency"
      - "bitcoin"
      - "ethereum"
      - "binance"
      - "cryptomarkets"
    client_id: "${REDDIT_CLIENT_ID}"
    client_secret: "${REDDIT_CLIENT_SECRET}"
    user_agent: "ATB-Trading-Bot/1.0"
    update_interval: 300  # 5 минут
  
  telegram:
    enabled: false
    bot_token: "${TELEGRAM_BOT_TOKEN}"
    channels:
      - "@crypto_news"
      - "@bitcoin_news"
      - "@ethereum_news"
    update_interval: 600  # 10 минут
  
  sentiment_analysis:
    multilingual: true
    context_aware: true
    real_time: true
    fear_greed_enabled: true
    trending_topics_enabled: true

# Новостной анализ
news_analysis:
  enabled: true
  sources:
    news_api:
      enabled: true
      api_key: "${NEWS_API_KEY}"
      update_interval: 300
    rss:
      enabled: true
      feeds:
        - "https://cointelegraph.com/rss"
        - "https://coindesk.com/arc/outboundfeeds/rss/"
        - "https://www.theblock.co/rss.xml"
        - "https://decrypt.co/feed"
        - "https://www.coindesk.com/arc/outboundfeeds/rss/"
      update_interval: 600
    twitter:
      enabled: false
      api_key: "${TWITTER_API_KEY}"
      update_interval: 300
  
  sentiment:
    threshold: 0.3
    impact_threshold: 0.5
    black_swan_keywords:
      - "hack"
      - "exploit"
      - "ban"
      - "regulation"
      - "collapse"
      - "bankruptcy"
      - "scam"
      - "rug pull"
      - "liquidation"
      - "margin call"
  
  social_media_integration:
    enabled: true
    weight: 0.3
    fear_greed_weight: 0.2
    trending_topics_weight: 0.1
    real_time_monitoring: true
