"""
Type stubs for ccxt library
"""

from typing import Any, Dict, List, Optional, Union
from datetime import datetime

class Exchange:
    """Base exchange class"""
    
    def __init__(self, config: Dict[str, Any]) -> None: ...
    
    async def load_markets(self) -> Dict[str, Any]: ...
    async def close(self) -> None: ...
    async def fetch_ohlcv(
        self, 
        symbol: str, 
        timeframe: str, 
        since: Optional[int] = None, 
        limit: Optional[int] = None
    ) -> List[List[Union[int, float]]]: ...
    async def create_order(
        self, 
        symbol: str, 
        type: str, 
        side: str, 
        amount: float, 
        price: Optional[float] = None, 
        params: Optional[Dict[str, Any]] = None
    ) -> Dict[str, Any]: ...
    async def cancel_order(self, order_id: str, symbol: Optional[str] = None) -> Dict[str, Any]: ...
    async def fetch_order(self, order_id: str, symbol: Optional[str] = None) -> Dict[str, Any]: ...
    async def fetch_balance(self, params: Optional[Dict[str, Any]] = None) -> Dict[str, Any]: ...
    async def fetch_positions(self, symbols: Optional[List[str]] = None) -> List[Dict[str, Any]]: ...

# Exchange classes
class binance(Exchange): ...
class bybit(Exchange): ...
class okx(Exchange): ...
class kucoin(Exchange): ...
class coinbase(Exchange): ...
class kraken(Exchange): ... 