{
    "generated": "2025-06-23T15:58:37.609118",
    "total_files": 7,
    "files_with_errors": 7,
    "total_errors": 7,
    "resolved_errors": 0,
    "unresolved_errors": 7,
    "fix_suggestions": 0,
    "files": {
        "C:\\Users\\Лариса\\Desktop\\ATB\\ATB\\create_circuit_breaker.py": {
            "total_errors": 1,
            "resolved_errors": 0,
            "unresolved_errors": 1,
            "fix_suggestions": 0,
            "last_analyzed": "2025-06-23T15:58:37.568232",
        },
        "C:\\Users\\Лариса\\Desktop\\ATB\\ATB\\infrastructure\\agents\\advanced_market_maker.py": {
            "total_errors": 1,
            "resolved_errors": 0,
            "unresolved_errors": 1,
            "fix_suggestions": 0,
            "last_analyzed": "2025-06-23T15:58:37.568232",
        },
        "C:\\Users\\Лариса\\Desktop\\ATB\\ATB\\infrastructure\\ml_services\\dataset_manager.py": {
            "total_errors": 1,
            "resolved_errors": 0,
            "unresolved_errors": 1,
            "fix_suggestions": 0,
            "last_analyzed": "2025-06-23T15:58:37.568232",
        },
        "C:\\Users\\Лариса\\Desktop\\ATB\\ATB\\interfaces\\presentation\\dashboard\\monitoring_dashboard.py": {
            "total_errors": 1,
            "resolved_errors": 0,
            "unresolved_errors": 1,
            "fix_suggestions": 0,
            "last_analyzed": "2025-06-23T15:58:37.568232",
        },
        "C:\\Users\\Лариса\\Desktop\\ATB\\ATB\\scripts\\check_system.py": {
            "total_errors": 1,
            "resolved_errors": 0,
            "unresolved_errors": 1,
            "fix_suggestions": 0,
            "last_analyzed": "2025-06-23T15:58:37.568232",
        },
        "C:\\Users\\Лариса\\Desktop\\ATB\\ATB\\shared\\dataset_manager.py": {
            "total_errors": 1,
            "resolved_errors": 0,
            "unresolved_errors": 1,
            "fix_suggestions": 0,
            "last_analyzed": "2025-06-23T15:58:37.568232",
        },
        "C:\\Users\\Лариса\\Desktop\\ATB\\ATB\\shared\\secure_config.py": {
            "total_errors": 1,
            "resolved_errors": 0,
            "unresolved_errors": 1,
            "fix_suggestions": 0,
            "last_analyzed": "2025-06-23T15:58:37.568232",
        },
    },
}
