"""
Infrastructure Layer - слой инфраструктуры.
"""

from typing import List

from .market_data import (
    BaseExchangeConnector,
    BinanceConnector,
    CoinbaseConnector,
    KrakenConnector,
)
from .messaging import (
    ErrorHandler,
    Event,
    EventBus,
    EventBusConfig,
    EventBusError,
    EventBusMetrics,
    EventBusProtocol,
    EventHandler,
    EventHandlerInfo,
    EventMetadata,
    EventPriority,
    EventType,
    HandlerConfig,
    Message,
    MessageHandler,
    MessageHandlerInfo,
    MessagePriority,
    MessageQueue,
    MessageQueueConfig,
    MessageQueueError,
    MessageQueueMetrics,
    MessageQueueProtocol,
    MessagingError,
    WebSocketConnection,
    WebSocketService,
    WebSocketServiceConfig,
    WebSocketServiceError,
    WebSocketServiceMetrics,
    WebSocketServiceProtocol,
    create_event,
    create_handler_config,
    create_message,
)
from .repositories import (
    InMemoryMarketRepository,
    InMemoryMLRepository,
    InMemoryPortfolioRepository,
    InMemoryRiskRepository,
    InMemoryStrategyRepository,
    InMemoryTradingRepository,
    PostgresMarketRepository,
    PostgresMLRepository,
    PostgresPortfolioRepository,
    PostgresRiskRepository,
    PostgresStrategyRepository,
    PostgresTradingRepository,
)

__all__: List[str] = [
    # Repositories
    "PostgresTradingRepository",
    "PostgresPortfolioRepository",
    "PostgresStrategyRepository",
    "PostgresMarketRepository",
    "PostgresRiskRepository",
    "PostgresMLRepository",
    "InMemoryTradingRepository",
    "InMemoryPortfolioRepository",
    "InMemoryStrategyRepository",
    "InMemoryMarketRepository",
    "InMemoryRiskRepository",
    "InMemoryMLRepository",
    # External Services
    "BybitExchangeService",
    "BinanceExchangeService",
    # Messaging
    "EventBus",
    "MessageQueue",
    "WebSocketService",
    "WebSocketConnection",
    "EventBusConfig",
    "MessageQueueConfig",
    "WebSocketServiceConfig",
    "EventPriority",
    "MessagePriority",
    "EventType",
    "Event",
    "Message",
    "EventMetadata",
    "EventHandler",
    "MessageHandler",
    "ErrorHandler",
    "HandlerConfig",
    "EventHandlerInfo",
    "MessageHandlerInfo",
    "EventBusProtocol",
    "MessageQueueProtocol",
    "WebSocketServiceProtocol",
    "EventBusMetrics",
    "MessageQueueMetrics",
    "WebSocketServiceMetrics",
    "MessagingError",
    "EventBusError",
    "MessageQueueError",
    "WebSocketServiceError",
    "create_event",
    "create_message",
    "create_handler_config",
    # Market Data
    "BinanceConnector",
    "CoinbaseConnector",
    "KrakenConnector",
    "BaseExchangeConnector",
    "market_profiles",
]
